services:
  - type: web
    name: mtg-nlp-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    # No environment variables needed - using built-in NLP parsing