services:
  - type: web
    name: mtg-nlp-search-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd mtg-nlp-search && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
